Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -56,37 +56,37 @@ runs:
         /tmp/accuknox-aspm-scanner tool install --type dast
         echo "✅ DAST tool installed"
 
-     - name: Run DAST scan
-       shell: bash
-          env:
-          ACCUKNOX_TOKEN: ${{ inputs.token }}
-          ACCUKNOX_LABEL: ${{ inputs.label }}
-          ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
-          TARGET_URL: ${{ inputs.target_url }}
-          SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
-          DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
-          SOFT_FAIL: ${{ inputs.soft_fail }}
-          run: |
-          set -e
-          mkdir -p /tmp/scan-dir
-          cd /tmp/scan-dir
-          
-          # Determine ZAP script
-          if [ "$DAST_SCAN_TYPE" = "full-scan" ]; then
+    - name: Run DAST scan
+      shell: bash
+      env:
+        ACCUKNOX_TOKEN: ${{ inputs.token }}
+        ACCUKNOX_LABEL: ${{ inputs.label }}
+        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
+        TARGET_URL: ${{ inputs.target_url }}
+        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
+        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
+        SOFT_FAIL: ${{ inputs.soft_fail }}
+      run: |
+        set -e
+        mkdir -p /tmp/scan-dir
+        cd /tmp/scan-dir
+
+        # Determine ZAP script
+        if [ "$DAST_SCAN_TYPE" = "full-scan" ]; then
           SCRIPT="zap-fullscan.py"
-          else
+        else
           SCRIPT="zap-baseline.py"
-          fi
-          
-          # Use container path for script
-          CMD="/zap/$SCRIPT -t $TARGET_URL -s $SEVERITY_THRESHOLD"
-          
-          SOFT_FAIL_ARG=""
-          if [ "$SOFT_FAIL" = "true" ]; then
+        fi
+
+        # Use container path for script
+        CMD="/zap/$SCRIPT -t $TARGET_URL -s $SEVERITY_THRESHOLD"
+
+        SOFT_FAIL_ARG=""
+        if [ "$SOFT_FAIL" = "true" ]; then
           SOFT_FAIL_ARG="--softfail"
-          fi
-          
-          echo "👉 Running DAST scan..."
-          echo "/tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command \"$CMD\" --container-mode"
-          
-          /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$CMD" --container-mode
+        fi
+
+        echo "👉 Running DAST scan..."
+        echo "/tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command \"$CMD\" --container-mode"
+
+        /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$CMD" --container-mode
